apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/issuer: "letsencrypt-DEPLOYMODE"
spec:
  tls:
  - hosts:
    - rlyapin.com
    secretName: letsencrypt-DEPLOYMODE-tls
  rules:
  - host: rlyapin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
