apiVersion: v1
kind: PersistentVolume
metadata:
  name: timescaledb-pv
spec:
  storageClassName: timescaledb-lsc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/psql"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: timescaledb-lsc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true