apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  selector:
    app: timescaledb
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: timescaledb-pv
spec:
  storageClassName: timescaledb-lsc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/psql"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: timescaledb-lsc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
spec:
  selector:
    matchLabels:
      app: timescaledb
  replicas: 1
  serviceName: "timescaledb"
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - image: timescaledb-image
        ports:
          - containerPort: 5432
        name: timescaledb
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: timescaledb-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescaledb-pv
  volumeClaimTemplates:
  - metadata:
      name: timescaledb-pv
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: timescaledb-lsc
      resources:
        requests:
          storage: 1Gi
