apiVersion: v1
kind: Service
metadata:
  name: timescaledb-service
spec:
  selector:
    name: timescaledb
  clusterIP: None

---

apiVersion: v1
kind: Pod
metadata:
  name: timescaledb-pod
  labels:
    name: timescaledb
spec:
  hostname: timescaledb-pod
  subdomain: timescaledb-service
  containers:
  - image: timescaledb-image
    ports:
      - containerPort: 5432
    name: timescaledb-pod
    env:
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: timescaledb-secrets
          key: POSTGRES_DB
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: timescaledb-secrets
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: timescaledb-secrets
          key: POSTGRES_PASSWORD
