apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-image
          ports:
            - containerPort: 3000
          envFrom:
          - secretRef:
              name: timescaledb-secrets
          - secretRef:
              name: redis-secrets
          env:
            - name: REDIS_URI
              value: "redis://$(REDIS_USER):$(REDIS_PASSWORD)@$(REDIS_HOSTNAME):$(REDIS_PORT)/$(REDIS_DBNUM)"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
