apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: default
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - env:
          - name: PGADMIN_DEFAULT_EMAIL
            valueFrom:
              secretKeyRef:
                name: pgadmin-secrets
                key: PGADMIN_DEFAULT_EMAIL
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgadmin-secrets
                key: PGADMIN_DEFAULT_PASSWORD
          - name: PGADMIN_PORT
            value: "80"
        image: dpage/pgadmin4
        name: pgadmin
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: 256Mi