apiVersion: apps/v1
kind: Deployment
metadata:
  name: psychic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psychic
  template:
    metadata:
      name: psychic
      labels:
        app: psychic
    spec:
      containers:
        - name: psychic
          image: psychic-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: timescaledb-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: psychic
spec:
  selector:
    app: psychic
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

