apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  serviceName: "redis"
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis-image
        command: ["redis-server", "/etc/redis.conf"]
        ports:
          - containerPort: 6379
        env:
          - name: REDISCLI_AUTH
            valueFrom:
              secretKeyRef:
                name: redis-secrets
                key: REDIS_PASSWORD
          - name: MASTER
            value: "true"
        volumeMounts:
            - mountPath: /data
              name: redis-pv
  volumeClaimTemplates:
  - metadata:
      name: redis-pv
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: redis-lsc
      resources:
        requests:
          storage: 128Mi
