apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      name: local-registry
      labels:
        app: local-registry
    spec:
      hostNetwork: true
      containers:
        - name: local-registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: local-registry
spec:
  selector:
    app: local-registry
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 31000
