apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  selector:
    app: timescaledb
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
spec:
  selector:
    matchLabels:
      app: timescaledb
  replicas: 1
  serviceName: "timescaledb"
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescaledb-image
        ports:
          - containerPort: 5432
        envFrom:
        - secretRef:
            name: timescaledb-secrets
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescaledb-pv
  volumeClaimTemplates:
  - metadata:
      name: timescaledb-pv
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: timescaledb-lsc
      resources:
        requests:
          storage: 1Gi
